import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
test('mesh pixel oracle: UV, seam, alpha, mixed order, reflection and resource lifetime',async({page})=>{
 await page.goto('/tests/render/browser/');await page.waitForFunction(()=>!!(window as any).meshHarness);
 const result=await page.evaluate(async()=>{
  const h=(window as any).harness,m=(window as any).meshHarness,u=h.unwrap,r=h.renderer;
  const bundle=await h.synthetic(),p=m.gridProject(bundle.project.assets[0],'synthetic');
  p.attachments[0].vertices=[-100,80,100,80,100,-80,-100,-80];p.attachments[0].uvs=[0,0,1,0,1,1,0,1];p.attachments[0].triangles=[0,1,2,0,2,3];p.attachments[0].weights=Array.from({length:4},()=>[{boneId:'root',weight:1}]);p.animations=[];bundle.project=p;
  const view={...h.viewport,width:400,height:320,zoom:1,background:'#00000000'};
  const pose=()=>u(h.evaluate(p,{animationId:null,time:0}));
  const pixel=async(x:number,y:number)=>{const png=u(await r.capture(pose(),view)),bitmap=await createImageBitmap(new Blob([png]));const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const ctx=c.getContext('2d')!;ctx.drawImage(bitmap,0,0);bitmap.close();return [...ctx.getImageData(x,y,1,1).data];};
  u(await r.prepare(bundle));
  const quadrants=[await pixel(140,110),await pixel(260,110),await pixel(140,210),await pixel(260,210)],outside=await pixel(50,50);
  const seam=await pixel(150,120);
  const refs=r.meshes.map((mesh:any)=>({mesh,geometry:mesh.geometry,buffers:[...mesh.geometry.buffers]}));
  const bitmap=r.resources.get('art').bitmap,texture=r.resources.get('art').texture;
  p.bones[0].setup.scaleX=-1;u(await r.prepare(bundle));const reflected=await pixel(260,110);
  const replacementReleased=refs.every((x:any)=>x.geometry.buffers===null&&x.buffers.every((b:any)=>b.destroyed)&&x.mesh.destroyed)&&texture.destroyed&&bitmap.width===0;
  p.bones[0].setup.scaleX=0;u(await r.prepare(bundle));const collapsed=await pixel(200,160);
  p.bones[0].setup.scaleX=1;
  p.attachments.push({id:'region',type:'region',assetId:'art',transform:{x:-20,y:20,rotation:0,scaleX:1,scaleY:1},width:200,height:160,pivotX:100,pivotY:80});
  p.slots.push({id:'region',name:'Region',boneId:'root',attachmentId:'region'});
  u(await r.prepare(bundle));const regionAbove=await pixel(180,130);
  p.slots.reverse();u(await r.prepare(bundle));const meshAbove=await pixel(180,130);
  p.slots=[{id:'mesh',name:'Mesh',boneId:'root',attachmentId:'mesh'},{id:'mesh2',name:'Mesh2',boneId:'root',attachmentId:'mesh'}];
  u(await r.prepare(bundle));const repeatedAlpha=await pixel(260,210);
  const malformed=pose();malformed.meshes[0].triangles[0]=999;const invalid=r.draw(malformed,view);
  const controller=new AbortController();controller.abort();const cancelled=await r.prepare(bundle,controller.signal);
  const retained=await pixel(140,110);
  const png=[...u(await r.capture(pose(),view))];
  const finalRefs=r.meshes.map((mesh:any)=>({mesh,geometry:mesh.geometry,buffers:[...mesh.geometry.buffers]}));const overlay=r.overlay;
  const gl=r.canvas.getContext('webgl2')||r.canvas.getContext('webgl');const loss=gl.getExtension('WEBGL_lose_context');loss.loseContext();
  await new Promise(resolve=>setTimeout(resolve,20));const lost=r.draw(pose(),view);
  r.dispose();const released=finalRefs.every((x:any)=>x.mesh.destroyed&&x.geometry.buffers===null&&x.buffers.every((b:any)=>b.destroyed))&&overlay.destroyed;
  return {quadrants,outside,seam,reflected,collapsed,regionAbove,meshAbove,repeatedAlpha,invalid,cancelled,retained,lost,replacementReleased,released,png};
 });
 expect(result.quadrants).toEqual([[255,0,0,255],[0,255,0,255],[0,0,255,255],[255,255,255,128]]);expect(result.outside).toEqual([0,0,0,0]);expect(result.seam).toEqual([255,0,0,255]);expect(result.reflected).toEqual([255,0,0,255]);expect(result.collapsed).toEqual([0,0,0,0]);expect(result.regionAbove).toEqual([0,255,0,255]);expect(result.meshAbove).toEqual([255,0,0,255]);expect(result.repeatedAlpha[3]).toBe(192);expect(result.invalid.ok).toBe(false);expect(result.cancelled.error.code).toBe('CANCELLED');expect(result.retained).toEqual([255,0,0,255]);expect(result.lost.error.code).toBe('RENDER_FAILED');expect(result.replacementReleased).toBe(true);expect(result.released).toBe(true);
 mkdirSync('evidence/issue-17',{recursive:true});writeFileSync('evidence/issue-17/synthetic.png',Buffer.from(result.png));const {png,...report}=result;void png;writeFileSync('evidence/issue-17/pixel-results.json',JSON.stringify(report,null,2)+'\n');
});
